kind = "web"
previewPath = "/"
title = "Urus Store"
version = "1.0.0"
id = "artifacts/urus-store"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22749

[services.development]
run = "pnpm --filter @workspace/urus-store run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/urus-store", "run", "build" ]
publicDir = "artifacts/urus-store/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22749"
BASE_PATH = "/"
